name: Continuous Integration
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POETRY_HTTP_BASIC_SAGACIFY_USERNAME: ${{ secrets.POETRY_HTTP_BASIC_SAGACIFY_USERNAME }}
      POETRY_HTTP_BASIC_SAGACIFY_PASSWORD: ${{ secrets.POETRY_HTTP_BASIC_SAGACIFY_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Validate commit messages
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: wagoid/commitlint-github-action@v3

      - name: cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-1.3.2-0

      - uses: snok/install-poetry@v1
        with:
          version: 1.3.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install packages & build
        run: |
          poetry install -E docs

      - name: Run formatter
        run: |
          poetry run black --check sagacify_llm_evaluation tests

      - name: Run linter
        run: |
          poetry run pylint sagacify_llm_evaluation tests

      - name: Run tests
        run: |
          poetry run pytest

      - name: Build documentation
        run: |
          mkdir gh-pages
          touch gh-pages/.nojekyll
          cd docs/
          poetry run sphinx-build -b html . _build
          cp -r _build/* ../gh-pages/

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: '*'
          folder: gh-pages
    