name: Continuous Integration

on:
  pull_request:

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POETRY_HTTP_BASIC_SAGACIFY_USERNAME: ${{ secrets.POETRY_HTTP_BASIC_SAGACIFY_USERNAME }}
      POETRY_HTTP_BASIC_SAGACIFY_PASSWORD: ${{ secrets.POETRY_HTTP_BASIC_SAGACIFY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Validate commit messages
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: wagoid/commitlint-github-action@v3

      - name: Cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-1.8.3-0

      - uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install packages & build
        run: |
          poetry install --without docs

      - name: Run formatter
        run: |
          poetry run black --check saga_llm_evaluation tests

      - name: Run linter
        run: |
          poetry run pylint saga_llm_evaluation tests

      - name: Run tests
        run: |
          poetry run pytest